### PR TITLE
Resolve the content type from the list/array of content-types.

### LINKED ISSUE #45: Plugin crashes when it receives Array type of content-type header.
**Logstash information**:

Please include the following information:

1. Logstash version (e.g. `bin/logstash --version`)
2. Logstash installation source (e.g. built from source, with a package manager: DEB/RPM, expanded from tar or zip archive, docker)
3. How is Logstash being run (e.g. as a service/service manager: systemd, upstart, etc. Via command line, docker/kubernetes)
4. How was the Logstash Plugin installed

**JVM** (e.g. `java -version`):

If the affected version of Logstash is 7.9 (or earlier), or if it is NOT using the bundled JDK or using the 'no-jdk' version in 7.10 (or higher), please provide the following information:

1. JVM version (`java -version`)
2. JVM installation source (e.g. from the Operating System's package manager, from source, etc).
3. Value of the `JAVA_HOME` environment variable if set.

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
- Create and run the server which returns list of content-type headers, example nodejs source
```
var http = require("http");

http.createServer(function (request, response) {
   response.writeHead(200, {'Content-Type': ['text/plain', 'logstash/custom-type']} );
   response.end('Hello World\n');
}).listen(8081);

console.log('Server running at http://127.0.0.1:8081/');
```
- Config Logstash with `filter-http` which calls and receives list of content-type headers
```
filter {
    http {
        url => "http://localhost:8081"
        target_body => "body"
        target_headers => "headers"
    }
}
```
- Run Logstash and observe the error

**Provide logs (if relevant)**:
```
[2023-03-15T11:36:25,372][ERROR][logstash.javapipeline    ][main] Pipeline worker error, the pipeline will be stopped 
{:pipeline_id=>"main", :error=>"(NoMethodError) undefined method `split' for [\"text/plain\", \"logstash/custom-type\"]:Array", 
:exception=>Java::OrgJrubyExceptions::NoMethodError, :backtrace=>
["RUBY.process_response(/Users/mashhur/Dev/elastic/logstash/logstash-plugins/logstash-filter-
http/lib/logstash/filters/http.rb:136)", "RUBY.filter(/Users/mashhur/Dev/elastic/logstash/logstash-plugins/logstash-filter-
http/lib/logstash/filters/http.rb:96)", "RUBY.do_filter(/Users/mashhur/Dev/elastic/logstash/logstash-
core/lib/logstash/filters/base.rb:159)", "RUBY.multi_filter(/Users/mashhur/Dev/elastic/logstash/logstash-
core/lib/logstash/filters/base.rb:178)", "org.jruby.RubyArray.each(org/jruby/RubyArray.java:1865)", 
"RUBY.multi_filter(/Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/filters/base.rb:175)", 
"org.logstash.config.ir.compiler.AbstractFilterDelegatorExt.multi_filter(org/logstash/config/ir/compiler/AbstractFilterDelegatorExt.ja
va:133)", "RUBY.start_workers(/Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/java_pipeline.rb:304)"], 
:thread=>"#<Thread:0x7fc1e9a8@/Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/java_pipeline.rb:134 sleep>"}

```

### PR DESCRIPTION
**Pull request by mashhurs**
## Release notes

[rn:skip] 

## What does this PR do?
Fixes the crash when plugin receives the `Content-Type` header as an `Array`. This change introduces a resolution of content type which supports: `array`, `string` and empty `string`.

## Why is it important/What is the impact to the user?
Some applications (example [apigateway-openlogging-elk](https://github.com/Axway-API-Management-Plus/apigateway-openlogging-elk)) is using a server which responses list of `Content-Type` media types.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files (and/or docker env variables)
- [x] I have added tests that prove my fix is effective or that my feature works

## Author's Checklist

- [ ]

## How to test this PR locally
- Clone the change
- Use following config
```
filter {
    http {
        url => "http://localhost:8081"
        target_body => "body"
        target_headers => "headers"
    }
}
```
- Run a server which returns Content-Type array
```
var http = require("http");

http.createServer(function (request, response) {
   response.writeHead(200, {'Content-Type': ['text/plain', 'logstash/custom-type']} );
   response.end('Hello World\n');
}).listen(8081);

console.log('Server running at http://127.0.0.1:8081/');
```

## Related issues
- Closes #45

### CODE REVIEW

File: lib/logstash/filters/http.rb [hunk 1]
```diff
@@ -132,9 +133,10 @@ def sprintf_object(event, obj)
   end
 
   def process_response(body, headers, event)
-    content_type, _ = headers.fetch("content-type", "").split(";")
     event.set(@target_headers, headers)
     return if @verb == 'head' # Since HEAD requests will not contain body, we need to set only header
+
+    content_type = resolve_content_type(headers)
```
Comment (kaisecheng) [inline lib/logstash/filters/http.rb:139]: Do you think we can check the array if "application/json" is one of the items and parse the body as json?
With multiple headers, I think "application/json" could be in any order.

Comment (mashhurs) [reply lib/logstash/filters/http.rb:139]: Yeah, since our interest is finding `application/json`, it also makes sense to _deep_ search.
```suggestion
    if headers_has_content_type?(headers, "application/json")
```


Remove L14 and `resolve_content_type` function will be replaced with
```
  def headers_has_content_type?(headers, looking_content_type)
    # content-type might be an array or string with ; separated
    content_types = headers.fetch("content-type", "")
    return content_types.include?(looking_content_type) unless content_types.kind_of?(Array)

    content_types.each do |content_type|
      return true if content_type.include?(looking_content_type)
    end
    false
  end
```

How do you think?

Comment (kaisecheng) [reply lib/logstash/filters/http.rb:139]:
```ruby
def headers_has_json?(headers) 
  return [ headers.fetch("content-type", "") ]
              .map{|i| i}
              .flatten
              .include?("application/json")
end
```

Comment (kaisecheng) [reply lib/logstash/filters/http.rb:139]: I forgot to split(';'), but leave it to you

Comment (mashhurs) [reply lib/logstash/filters/http.rb]: Simplified with [this commit](https://github.com/logstash-plugins/logstash-filter-http/pull/46/commits/526d39f6ec34694da04737b9266fa5d104b1de9c).

File: lib/logstash/filters/http.rb [hunk 2]
```diff
@@ -152,4 +153,15 @@ def process_response(body, headers, event)
...
+  # @param headers [String] or [Array]
+  # @return resolved content-type
+  def headers_has_json_content_type?(headers)
+    # content-type might be an array or string with ; separated
+    [ headers.fetch("content-type", "") ]
+             .map {|i| i }
+             .flatten
+             .include?("application/json")
+  end
+
```
Comment (kaisecheng) [inline lib/logstash/filters/http.rb:166]:
```suggestion
  ##
  # @param headers [String] or [Array]
  # @return boolean
  def headers_has_json_content_type?(headers)
    # content-type might be an array or string with ; separated
    headers = headers.kind_of?(Array) ? headers : headers.split(';')
    return headers.map(&:strip).include?("application/json")
  end

```

**Review by kaisecheng — COMMENTED** [review]
Left one suggestion to split the headers when it is a string

File: lib/logstash/filters/http.rb (hunk 2 above)
Comment (mashhurs) [reply lib/logstash/filters/http.rb:166]: I have updated the suggestion with working (locally tested) version.

**Review by kaisecheng — APPROVED** [review]
Thanks for fixing the issue. LGTM
